language: python
python: "2.7"
virtualenv:
  system_site_packages: true
before_install:
  # For Pandas version 0.14.
  # See https://launchpad.net/~pythonxy/+archive/ubuntu/pythonxy-devel?field.series_filter=saucy
  - sudo add-apt-repository "deb http://ppa.launchpad.net/pythonxy/pythonxy-devel/ubuntu saucy main" -y
  - sudo apt-get update -qq
  - sudo apt-get install python-numpy python-pandas python-tables python-yaml
install:
  - pip install flake8  # Not yet available in Debian stable
  - pip install sas7bdat
  - pip install click
  - pip install -r requirements.txt
script: make test-ci
