version: 2
jobs:
  build_python3:
    docker:
      - image: python:3.7

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-apt-{{ checksum "setup.py" }}

      - restore_cache:
          key: v1-py3-venv-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Install HDF5
          command: |
            apt-get update
            apt-get -y install libhdf5-serial-dev

      - run:
          name: Create a virtualenv
          command: |
            mkdir -p /tmp/venv/openfisca-survey-manager
            python -m venv /tmp/venv/openfisca-survey-manager
            echo "source /tmp/venv/openfisca-survey-manager/bin/activate" >> $BASH_ENV

      - run:
          name: Install dependencies
          command: |
            make install
            # pip install --editable git+https://github.com/openfisca/openfisca-core.git@BRANCH#egg=OpenFisca-Core[web-api]  # use a specific branch of OpenFisca-Core
            pip install coveralls

      - save_cache:
          key: v1-py3-venv-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - /tmp/venv/openfisca-france-data

      - save_cache:
          key: v1-py3-apt-{{ checksum "setup.py" }}
          paths:
            - /var/cache/apt/archives

      - run:
          name: Run tests
          command: |
            make test
            coveralls

      - run:
          name: Check version number has been properly updated
          command: |
            git fetch
            .circleci/is-version-number-acceptable.sh

  deploy_python3:
    docker:
      - image: python:3.7

    environment:
      PYPI_USERNAME: openfisca-bot  # Edit this value to replace it by your Pypi username
      # PYPI_PASSWORD: this value is set in CircleCI's web interface; do not set it here, it is a secret!

    steps:
      - checkout

      - restore_cache:
          key: v1-py3-venv-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: Check for functional changes
          command: if ! .circleci/has-functional-changes.sh ; then circleci step halt ; fi

      - run:
          name: Upload a Python package to Pypi
          command: |
            source /tmp/venv/openfisca-survey-manager/bin/activate
            .circleci/publish-python-package.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_python3
      - deploy_python3:
          requires:
            - build_python3
          filters:
            branches:
              only: master
